/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DaysList: typeof import('./src/components/DaysList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignatureField: typeof import('./src/components/SignatureField.vue')['default']
    StudentList: typeof import('./src/components/StudentList.vue')['default']
    Test: typeof import('./src/components/Test.vue')['default']
  }
}
